### PR TITLE
Install AForge through NuGet & drop unused Math.Net.Numerics package

### PR DESCRIPTION
**Pull request by dbolkensteyn**
Simplify the steps to build the project by:
1. Installing AForge.NET through NuGet
2. Removing the unused MathNet.Numerics package

Ideally, the whole `packages` folder should be ignored in the repo, but `HomographyEstimation.dll` doesn't seem to be available through NuGet.

### CODE REVIEW

**Comment by jkuusama** [comment]
I did not write HomographyEstimation.dll, I bought it. Therefore it or its source code is not publicly available.

**Comment by hanneseilers** [comment]
> Installing AForge.NET through NuGet
Was fixed with merge #50 
>Removing the unused MathNet.Numerics package
Still needed.

**Comment by jkuusama** [comment]
Thank you!

 

Best regards

 

Juha

**Comment by windywake** [comment]
> I did not write HomographyEstimation.dll, I bought it. Therefore it or its source code is not publicly available.



> I did not write HomographyEstimation.dll, I bought it. Therefore it or its source code is not publicly available.

Dear Sir,
Could you tell me where you buy HomographyEstimation.dll module? Thanks.

**Pull request closed without merging**
