### PR TITLE
Place Parts manually assisted

### PR DESCRIPTION
**Pull request by petegit**
Additional methode for Tape based and Loose Part placement. Allows to manually correct part position during placement process. 
Part is picked and moved above (2mm)  board placement position. After manually fine tuning of the position ENTER triggers final placement of the part. The new placment methodes are _Place Assisted_ and _Loose Part Assisted_.

### CODE REVIEW

**Comment by petegit** [comment]
Would be nice to have this in the main development line.

**Comment by jkuusama** [comment]
Looks great, I really appreciate! This didn't made it to the previous release, it was put out in a hurry as there was a bug that was holding a customer back. I'll test this asap and put it out

**Comment by madcowswe** [comment]
This looks like a very nice feature especially if you aren't certain of the pickup-points from the CAD. @jkuusama can you see if you can get this merged?

**Comment by petegit** [comment]
Merged

**Pull request closed without merging**
