### PR TITLE
Needle Wobble correction using CNC domain

### PR DESCRIPTION
**Pull request by sgraves**
There are several changes to the needle wobble algorithms.
The Offset2Method_button_Click function was the first to be changed
and has an extensive discussion at the top.  The biggest change is to
store the current CNC position in the needle CalibrationPoints array.
The CNC position of the down camera over the up camera is calculated
(we can't actually move there) and is used to calculate the Needle Offset
for every calibration point.  The interpolation routines still work.
The other big change is to programmatically move the needle to the
center of the camera for every measurement.  This should give the highest
accuracy in the CNC domain.  Finally, the "Set" button has been removed
for the Up Camera location.  It is set as part of the Needle Setup.

### CODE REVIEW

**Comment by secondaryObject** [comment]
Hello, 

I'm looking into the changes of the calibration and wondering why isn't it better to actually have a center of the rotation as the calibrated position of the head. That shall be very stable thing. So the calibration procedure for this could be almost the same but with small change at the end:

1) go over the some position with down-looking camera
2) move needle to the same position (we have an offset from camera to the needle rotated by specified angle)
3) we move the needle to the up-looking camera and center with an algorithm to get down-looking seeing exact center of the nozzle

Here I would add needle wobble calibration and compute the distance between needle rotated in the angle in step 2 /3 and center of the rotation of the so called mount head. This we could use to know the exact distance between down-looking camera and center of rotation. Also this position could be stored as up-looking camera position instead.

When having center of rotation of the mount head we shall not need to calibrate needle wobble at all. The PnP will most likely pick the part in the center of rotation and probably also place it correctly even if it rotates. 

Here we could at the end have two problems:

1) If the needle is very tilted (distance between center of rotation and actual center of nozzle too big) it could miss to pick the part or pick it billboarded / pick it at the corner which is dangerous. 
2) When there is a pick offset the machine will more likely fail to rotate it into the correct position / angle but this problem is present even now.

What do you think about this?

Regards
Martin

**Comment by jkuusama** [comment]
Hi,

I haven’t tried it, so these are my opinions, not proven facts. I think that using the center of rotation as a reference should eventually lead to the same result. I am so familiar with the current method that the alternative feels -for me- less intuitive and more complicated (which it might be for other people, of course). The center of rotation is likely stable as you said, but the location of the up cam is at least as stable:-).

My thinking is that we are really concerned about only where the needle tip is. In the current calibration method, we find out the nominal needle to down cam difference, defined as the difference between down cam cross location and needle tip at measurement Z level. (This is 0.5mm above PCB surface; we don’t have 3d calibration, so the 0.5mm is a guess of average small component height. If calibration and other things are perfect, this results to the needle tip being exactly at the right place 0.5mm above PCB, so a 0.5mm high component is exactly at right position.)

In calibration process, we also find out the position of the up cam, defined as the location where a perfect needle, requiring no correction, at measurement Z level, is at the center of the up cam view. Of course, this perfect needle is what you had in the calibration process and no correction was applied.

If the needles and the mechanics would be perfect, the needle tip wouldn’t move if changed or rotated. The nominal down cam to needle offset would always be true and taking the needle above the up cam at measurement Z, it would always be at the center. This is not the case, so we measure how much it is off at several angles (and interpolate the between values).

In my brain, this is the simplest thinking. We are really moving the needle, and this method finds out where the tip is, with simple operations. It is also easy to debug, as you can measure all the numbers directly.

Best regards

Juha

**Comment by sgraves** [comment]
Juha,
I agree that your needle correction works except for one small problem (it results in approximately a 0.2 mm error on my machine).  The problem is that the location that the optical system gives is not centered on the cross hair.  On my machine it is about 0.2mm to the left.  I have not been able to determine why the optical system does not use the center of the image as 0,0.  It doesn't make sense.  The down camera does not exhibit the same issue.  In any case, I started by changing the offset calibration code to programmatically move the needle to the optical 0,0.  This results in the correct calculation for the up camera.  This needs to be correct since all of the needle corrections are made using the camera.  Once I had used the moving to the center technique (in place of the human moving to the cross hairs), I realized that the closer one is to the center, the more accurate the optical measurements are.  For one, the mm/pixel values must be exact, any inaccuracy in them will show up as needle error and the human who created them can easily not be precise when doing the calibration.  And two, the mm/pixel value actually changes with distance from the center.  Zooming minimizes the effect, but a camera will have a parallax effect.  As one moves away from the center the actual mm/pixel will increase.  When you use a scale and do the calibration, you are just getting the average mm/pixel across that span.  The actual value for individual pixels will be above and below that value depending on how close to the center they are.

BTW Welcome back.

Steve

**Comment by sgraves** [comment]
Juha,
Another part of my changes is turning on the up camera while doing the calibration.  Personally, it gives some feedback about what is happening that was not being used.  I feel like more feedback makes troubleshooting easier.  I have code I haven't added to the branch where one can do a needle verification.  Using that we found that the smaller needles are almost immediately knocked out of calibration.  The verification uses the needle move method to move the needle over the up camera.  When the needle is correctly calibrated it moves to the center after each rotation. However, when the needle is out of calibration one can see that the needle does not move back to the center.  It is very clear when a needle is calibrated and when it isn't.  In any case, I also measure the errors and print an error report to the log.

I am very busy right now getting my first board working.  Then I will put some more changes out there for your perusal.

Steve

**Comment by jkuusama** [comment]
Outdated, forgot to close.

**Pull request closed without merging**
